# -*- coding: utf-8 -*-
"""PIAIC_Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTub2vDbbUIsNnzyel0vJS7I11scwuNy

Exercise 3-1 : Names
"""

list_Friends = ['Talha','Waqee','Bilal']
print(list_Friends[0])
print(list_Friends[1])
print(list_Friends[2])

"""Exercise 3-2 : Greetings"""

print('Name of Friend is:',list_Friends[0])
print('Name of Friend is:',list_Friends[1])
print('Name of Friend is:',list_Friends[2])

"""Exercise 3-3: Your Own List"""

list_Cars = ['Sonata','Sportage','Haval']
print('I would Like to own a ',list_Cars[0])
print('I would Like to own a ',list_Cars[1])
print('I would Like to own a ',list_Cars[2])

"""Exercise 3-4: Guest List"""

list_Persons = ['Seveerus Snape','Bruce Wayne','Albus Dumbledore']
print('I would like to invite ',list_Persons[0], ' for the dinner!')
print('I would like to invite ',list_Persons[1], ' for the dinner!')
print('I would like to invite ',list_Persons[2], ' for the dinner!')

"""Exercise 3-5: Changing Guest List"""

print(list_Persons[0],' is not available for the dinner today!')
list_Persons[0]='Sirius Black'
print('I would like to invite ', list_Persons[0], 'for the Dinner')
print('I would like to invite ', list_Persons[1], 'for the Dinner')
print('I would like to invite ', list_Persons[2], 'for the Dinner')

"""Exercise 3-6: More Guests"""

print('I would like to inform my Guests that we got a bigger table for Dinner and would like to invite some more Guests at Dinner today!')
list_Persons.insert(0,'Bilbo Baggins')
list_Persons.append('Captain Jack Sparrow')
list_Persons.insert(3,'Dr Strange')
print('Now I would like to invite ', list_Persons[0], 'for the Dinner')
print('Now I would like to invite ', list_Persons[1], 'for the Dinner')
print('Now I would like to invite ', list_Persons[2], 'for the Dinner')
print('Now I would like to invite ', list_Persons[3], 'for the Dinner')
print('Now I would like to invite ', list_Persons[4], 'for the Dinner')
print('Now I would like to invite ', list_Persons[5], 'for the Dinner')

"""Exercise 3-7: Shrinking Guest List"""

print('I am very Sorry about the Bad news that our bigger table would not reach at the Dinner, so we have to reduce the List of Guests to 2 people only for the Dinner!')
out=list_Persons.pop()
print('I am very Sorry ',out,' your Invitation is drawn!')
out=list_Persons.pop()
print('I am very Sorry ',out,' your Invitation is drawn!')
out=list_Persons.pop()
print('I am very Sorry ',out,' your Invitation is drawn!')
out=list_Persons.pop()
print('I am very Sorry ',out,' your Invitation is drawn!')
print(list_Persons[0], 'You are still invited for the Dinner!')
print(list_Persons[1], 'You are still invited for the Dinner!')

del list_Persons[0]
del list_Persons[0]

"""Exercise 3-8: Seeing the World"""

List_Places=['Alaska','Saint Helena','Svalbard','Amazon','Maasai Mara National Reserve']
print('Original List is: ',List_Places[0],',',List_Places[1],',',List_Places[2],',',List_Places[3],',',List_Places[4])


Copy_Places = List_Places.copy()
Copy_Places.sort()
print('Ordered List is: ',Copy_Places[0],',',Copy_Places[1],',',Copy_Places[2],',',Copy_Places[3],',',Copy_Places[4])

print('Again Original List is: ',List_Places[0],',',List_Places[1],',',List_Places[2],',',List_Places[3],',',List_Places[4])

Copy_Places.sort(reverse=True)
print('Reverse List is: ',Copy_Places[0],',',Copy_Places[1],',',Copy_Places[2],',',Copy_Places[3],',',Copy_Places[4])


print('Again Original List is: ',List_Places[0],',',List_Places[1],',',List_Places[2],',',List_Places[3],',',List_Places[4])

List_Places.reverse()
print('Original List is After Reverse is: ',List_Places[0],',',List_Places[1],',',List_Places[2],',',List_Places[3],',',List_Places[4])

List_Places.reverse()
print('Original List is After 2nd Reverse is: ',List_Places[0],',',List_Places[1],',',List_Places[2],',',List_Places[3],',',List_Places[4])

List_Places.sort()
print('Original List is After Sorting is: ',List_Places[0],',',List_Places[1],',',List_Places[2],',',List_Places[3],',',List_Places[4])


List_Places.sort(reverse = True)
print('Original List is After Revrse Sorting is: ',List_Places[0],',',List_Places[1],',',List_Places[2],',',List_Places[3],',',List_Places[4])

"""Exercise 3-9: Dinner Guests"""

print('I am inviting ',len(list_Persons), 'No of people to dinner')

"""Exercise 3-10: Every Function"""

list_River=['Ravi','Indus','Jehlum','Chenab']
list_River.count(3)
list_River.extend('kabul')
list_River.index('Indus')
list_River.append('Sutlej')
list_River.remove('Ravi')
list_River.sort()
list_River.reverse()
list_River.clear()

"""Exercise 3-11: Intentional Error"""

#list_Cars[3] = 'BMW'
#Corrected Index After Error
list_Cars[0]='BMW'